### ISSUE TITLE
How to change the line of two nodes to a curve or two non-coincident parallel lines

### ISSUE THREAD

**Issue by xc1318005971** [zakjan/pixi-graph#6]

**Comment by xc1318005971** [comment]
Can you replace a straight line with a curved line

**Comment by zakjan** [comment]
Hi, I'm sorry but curved lines are not supported yet. It's on the roadmap though. Thank you for filling in the survey!

**Comment by xc1318005971** [comment]
If the curve is not good, can a straight line be used? The main purpose is to separate the two overlapping lines in the routine. Is there a way?

**Comment by xc1318005971** [comment]
I very very very need it

**Comment by zakjan** [comment]
As much as I would like to be able to help you, this library is not ready yet to support curved or parallel edges, and my priorities are elsewhere currently. If you depend on it in a production application, would you mind if I ask you to [get in touch directly](https://zakjan.cz/) to discuss a possibility of sponsored development? Otherwise I would recommend to switch to another library. Thanks for your comprehension.
